# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UipathVB-Orch'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    runWorkflowAnalysis: true
    traceLevel: 'Information'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UipathVB-Orch'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'CICD'
    traceLevel: 'Information'
